Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"

  config.vm.define "qbornetS" do |controller|
    controller.vm.hostname = "qbornetS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    controller.vm.synced_folder ".", "/vagrant", disabled: false
    controller.vm.provider :virtualbox do |vb|
      vb.name = "qbornetS"
      vb.cpus = 1
      vb.memory = 1024
    end
    controller.vm.provision "shell", inline: <<-SHELL
      mkdir -p /etc/rancher/k3s
      cp /vagrant/confs/config.yaml /etc/rancher/k3s
      curl -sfL https://get.k3s.io | sh -
      sleep 15
      kubectl apply -f /vagrant/confs/deployment.yaml
    SHELL
  end
end
