Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"

  config.vm.define "qbornetS" do |controller|
    controller.vm.hostname = "qbornetS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    controller.vm.synced_folder ".", "/vagrant", disabled: false
    controller.vm.provider :virtualbox do |vb|
      vb.name = "qbornetS"
      vb.cpus = 1
      vb.memory = 1024
    end
    controller.vm.provision "shell", path: "./scripts/controller.sh"
  end

  config.vm.define "qbornetSW" do |worker|
    worker.vm.hostname = "qbornetSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.synced_folder ".", "/vagrant", disabled: false
    worker.vm.provider :virtualbox do |vb|
      vb.name = "qbornetSW"
      vb.cpus = 1
      vb.memory = 1024
    end
    worker.vm.provision "shell", path: "./scripts/worker.sh"
  end
end
